baseURL: "https://cesar-jimenez.com"
languageCode: "en-us"
title: "Cesar Jimenez"
pygmentsstyle: 'monokai'

# Theme settings
theme: novela
# module:
#   imports:
#     - path: "github.com/forestryio/hugo-theme-novela"
paginate: 6
social:
  twitter: "https://twitter.com/cesar_r_jimenez"
  github: "https://github.com/Numbers88s"
  # instagram: "#"
  linkedin: "https://linkedin.com/in/cesarrjimenez"
  # dribbble: "#"
  # youtube: "#"
taxonomies:
  author: authors
